-- DGStation FINAL BUILD database
create extension if not exists pgcrypto;
create table if not exists profiles(id uuid primary key references auth.users(id) on delete cascade, member_id text unique not null default ('DG'||lpad((floor(random()*999999))::int::text,6,'0')), username text unique not null, mobile text, bank_name text, bank_account text, role text not null default 'member' check(role in ('member','admin','owner')), status text not null default 'active' check(status in ('active','inactive')), wallet numeric(12,2) not null default 0, created_at timestamptz default now());
create table if not exists game_accounts(id uuid primary key default gen_random_uuid(),user_id uuid references profiles(id) on delete cascade,platform text not null,game_id text,unique(user_id,platform));
create table if not exists transactions(id uuid primary key default gen_random_uuid(),user_id uuid references profiles(id) on delete cascade,type text not null check(type in ('deposit','withdraw')),amount numeric(12,2) not null,bank text,platform text not null,bonus text,receipt_urls text[] default '{}',admin_receipt_url text,remark text,status text not null default 'pending' check(status in ('pending','approved','rejected')),created_at timestamptz default now(),updated_at timestamptz default now());
create unique index if not exists one_pending_withdraw on transactions(user_id) where type='withdraw' and status='pending';
create table if not exists messages(id uuid primary key default gen_random_uuid(),user_id uuid references profiles(id) on delete cascade,sender_id uuid references profiles(id),body text not null,kind text not null default 'chat',created_at timestamptz default now());
create table if not exists promotions(id uuid primary key default gen_random_uuid(),title text not null,description text,active boolean default true,min_deposit numeric(12,2),turnover numeric(6,2),max_withdraw_multiplier numeric(6,2),slot_only boolean default false,start_time time,end_time time,created_at timestamptz default now());
alter table profiles enable row level security; alter table game_accounts enable row level security; alter table transactions enable row level security; alter table messages enable row level security; alter table promotions enable row level security;
create or replace function is_staff() returns boolean language sql security definer stable as $$select exists(select 1 from profiles where id=auth.uid() and role in ('admin','owner'))$$;
drop policy if exists "profile self/staff" on profiles; create policy "profile self/staff" on profiles for select using(id=auth.uid() or is_staff());
drop policy if exists "game self/staff" on game_accounts; create policy "game self/staff" on game_accounts for select using(user_id=auth.uid() or is_staff());
drop policy if exists "tx read self/staff" on transactions; create policy "tx read self/staff" on transactions for select using(user_id=auth.uid() or is_staff());
drop policy if exists "tx member insert" on transactions; create policy "tx member insert" on transactions for insert with check(user_id=auth.uid());
drop policy if exists "msg read self/staff" on messages; create policy "msg read self/staff" on messages for select using(user_id=auth.uid() or is_staff());
drop policy if exists "msg insert self/staff" on messages; create policy "msg insert self/staff" on messages for insert with check(user_id=auth.uid() or is_staff());
drop policy if exists "promo public read" on promotions; create policy "promo public read" on promotions for select using(active=true or is_staff());
insert into promotions(title,description,min_deposit,turnover,max_withdraw_multiplier,slot_only) select 'Welcome Back','1x claim • Max Bonus RM388',30,3,50,false where not exists(select 1 from promotions where title='Welcome Back');
insert into promotions(title,description,min_deposit,turnover,slot_only,start_time,end_time) select 'Midnight Bonus 20%','20% • Slot Only',10,2,true,'00:00','05:00' where not exists(select 1 from promotions where title='Midnight Bonus 20%');